"""initial schema

Revision ID: 64fc8e98c0de
Revises: 
Create Date: 2025-06-08 21:04:19.996111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64fc8e98c0de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('profile_pic_url', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('blocks',
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followee_id', sa.Integer(), nullable=False),
    sa.Column('followed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followee_id'], ['profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id')
    )
    op.create_table('tweets',
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited_at', sa.DateTime(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('tweet_id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.tweet_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('likes',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('liked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.tweet_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    op.create_table('retweets',
    sa.Column('retweet_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('retweeted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.tweet_id'], ),
    sa.PrimaryKeyConstraint('retweet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retweets')
    op.drop_table('likes')
    op.drop_table('comments')
    op.drop_table('tweets')
    op.drop_table('follows')
    op.drop_table('blocks')
    op.drop_table('profiles')
    # ### end Alembic commands ###
